let movies = [
    {
          id: 1,
          title: "Matrix Recargadoje al paraiso",
          rating: 7,
          awars: 3,
          length: 120,
          price: 100,
          genre: "Acción",
    },
    {
          id: 2,
          title: "Viaje al paraiso",
          rating: 5,
          awars: 3,
          length: 90,
          price: 120,
          genre: "Suspenso.",
    },
    {
          id: 3,
          title: "Harry Potter y las Reliquias de la Muerte – Parte 2",
          rating: 1,
          awars: 10,
          length: 130,
          price: 150,
          genre: "Aventuras",
    },
    {
          id: 4,
          title: "Kung Fu Panda",
          rating: 3,
          awars: 2,
          length: 100,
          price: 95,
          genre: "Comedia",
    },
    {
          id: 5,
          title: "El señor de los anillos 3: El retorno del rey",
          rating: 2,
          awars: 7,
          length: 210,
          price: 180,
          genre: "Ciencia Ficción",
    },
    {
          id: 6,
          title: "Rambo",
          rating: 3,
          awars: 2,
          length: 100,
          price: 95,
          genre: "Acción",
    },
    {
          id: 7,
          title: "Sexto Sentido",
          rating: 2,
          awars: 7,
          length: 210,
          price: 180,
          genre: "Suspenso.",
    },
    {
          id: 8,
          title: "Una de guerra",
          rating: 3,
          awards: 7,
          length: 95,
          price: 99,
          genere: "Acción",
    },
    {
          id: 9,
          title: "Tarzan",
          rating: 5,
          awards: 0,
          length: 89,
          price: 15,
          genere: "Aventura",
    },
    {
          id: 10,
          title: "Volver al Futuro",
          rating: 10,
          awards: 15,
          length: 118,
          price: 65,
          genere: "Ciencia Ficción",
    },
    {
          id: 11,
          title: "Scary movie",
          rating: 7,
          awards: 2,
          length: 108,
          price: 29,
          genere: "Comedia",
    },
    {
          id: 12,
          title: "Space Jam",
          rating: 9,
          awards: 4,
          length: 120,
          price: 32,
          genere: "Animación",
    },
];

module.exports = movies;